version: '3'

networks:
  keycloak-network:

volumes:
    keycloak-postgres-data:
    keycloak-nginx-ssl:

services:
  keycloak:
    image: ernsheong/keycloak-postgres
    container_name: keycloak
    networks:
      - keycloak-network
    depends_on:
      - postgres
    environment:
      - POSTGRES_DATABASE=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak
      - PROXY_ADDRESS_FORWARDING=true
  nginx:
    image: ernsheong/keycloak-nginx
    container_name: nginx